package com.rock.iscreenblsdk

import android.app.Application
import android.content.Context
import com.rockstreamer.iscreensdk.utils.ISCREEN_SHAREDPREFERANCE
import com.rockstreamer.iscreensdk.utils.iScreenSDKInit
import com.rockstreamer.iscreensdk.utils.loginState

class App: Application() {

    override fun onCreate() {
        super.onCreate()
        loginState = getSharedPreferences(ISCREEN_SHAREDPREFERANCE, Context.MODE_PRIVATE)
        iScreenSDKInit(apiToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjQ3MTksInByb3ZpZGVyX2lkIjoiKzg4MDE5MjQzNTQ0MjQiLCJyb2xlIjowLCJ1c2VybmFtZSI6Iis4ODAxOTI0MzU0NDI0IiwicGxhdGZvcm0iOiJpc2NyZWVuIiwicGFydG5lciI6IkJBTkdMQUxJTktfTVlCTCIsInN1YnNjcmliZSI6ZmFsc2UsInBhY2thZ2VJbmZvIjpudWxsLCJpc1RWT0QiOmZhbHNlLCJ0dm9kRXhwaXJlRGF0ZSI6IjE5NzAtMDEtMDEiLCJpYXQiOjE3NjUyNzY3OTUsImV4cCI6MTc2NTMwMzE5OX0.JFo9cupUb9xROykHkSzdsZK2zcvOdyRMyUOx_0U2ylQaaXK7XT10W74ikDWcszwt7P86cnoRRBx_b6Ud2pYJ4pECuRlLavrBlRmYri3Ji-Utone45sQyh7MYeIwiFXiQoWQO-KrFgYMjguzMoLAIyfj8J1oMo39gsCzTkUNptPOWGdaXGqU6uYxPTEk9iIhsrtEKIXALQet692g1Qn6Y-840lprpo-3WWJQ0pyPfpSd6WdZNnRUt7RRxZsh-7WVMKGHebBKOwOGgFh12r9gGDWtxpoYuOCvRnGQizbeCHTjLyvXEkPKIHM-OTAw6ZGkHbMhGJqYGhOen0UNLru7FExQwLW_sv6VM02G8nef-gxhFEsLHEZRTZ4f3NewBdQMGoXKLB1g7i90h3vR0G-StBQqH_deqXc0pxkGdnKyXyPxuxZ19pGf3BoKZenS7AKrwozXpvgwOusYgxv08ZY6P10b0a8Vuekrhn-efxrc1p77aJlbMdUJyrU3ZX30TfpTX-tKLQBlz3Zgd5KGN7N56SrziJlr5E_nvPJ2fFe9-EgCo1Mf-g_Ke57uyv-6ApxCh58d4SERLLwrvssg4SWN-2_osrw0_t5gsLFT-yxz4up9vldUrCGLGvP5UGD4CcMknDk1TjTYQBGvskqFXg3n7eeyY17FaLojiSJ1k3ye8Td0")
    }
}