package com.rock.iscreenblsdk

import android.app.Application
import android.content.Context
import com.rockstreamer.iscreensdk.utils.ISCREEN_SHAREDPREFERANCE
import com.rockstreamer.iscreensdk.utils.iScreenSDKInit
import com.rockstreamer.iscreensdk.utils.loginState

class App: Application() {

    override fun onCreate() {
        super.onCreate()
        loginState = getSharedPreferences(ISCREEN_SHAREDPREFERANCE, Context.MODE_PRIVATE)
        iScreenSDKInit(apiToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTI2NDgsInByb3ZpZGVyX2lkIjoiMTAwMCIsInJvbGUiOjAsInVzZXJuYW1lIjoiYXNoaWt1ckBleGFtcGxlLmNvbSIsInBsYXRmb3JtIjoiaXNjcmVlbiIsInN1YnNjcmliZSI6ZmFsc2UsInBhY2thZ2VJbmZvIjpudWxsLCJpc1RWT0QiOmZhbHNlLCJwYXJ0bmVyIjoiQkFOR0xBTElOS19NWUJMIiwidHZvZEV4cGlyZURhdGUiOiIxOTcwLTAxLTAxIiwiaWF0IjoxNzc1NTU4NDg1LCJleHAiOjE3NzU1NTg1NDV9.juEg4iGagLaaWpfo97st4Km9F5T4_8l56LVQkuRcBmEfV-e1oKeytGH9v3dD1vbxVfpjLC-mKmmPAYl8DRpnUuGFdipTGgTCSgdCwLP3TP73XrHToK25B4whRcEc8iK7VVwmCAI5XrroGHnHDZYH6HvpLBcaVi1_Un4OFss3fxFCbr6Um4mRKT9seSzU4c_AGZl9MjPwaNY6Oj0zgfxi0DGvqNVBtJdz1t9X7rCuDO_6a5ysg-ZYgNxRNIs-O6uPkxMnTsUVAPGMyFZYIAxSUaJZfLyJnRuHWtC2oJGGoRyUdrw-db2LNfMeGqydXPk2Zh31738TQOKVAMHmEuvP06uQtyDtsUZq0jyh-KX0WvgRf07773DvtCp7aPmdLUG0ImLgusf_fUECVk3kfzXcRbn1j-gySYSenpMEXXP5zeYK8dPtSnUcLfWBG3e7teaGU0o9F5wjwitb0nb_mtvCumd4FtC5OSaPkz6MxtqTtrtFUKCDoax5rGWjVUIZJ2n61lLWwqt6Gdjq1ZC826q8wKzgXQWXGmsGIpcrGnvqRaQQQO-9n4-8ozaQ4NtFSzFj71g4cMYE0HxNDd6ZpCOVY4QYaf498h1GLFMjreRVHo-yelrD0WKpBNydLY2SMAuC2IDozUVkQjaZXW3GXfKBFqSAaL8Y6na6OsLUR_twNy0")
    }
}