package com.rockstreamer.koinandroidexample

import android.app.Application
import android.content.Context
import com.rockstreamer.iscreensdk.di.contentModule
import com.rockstreamer.iscreensdk.di.networkModule
import com.rockstreamer.iscreensdk.di.viewModelModule
import com.rockstreamer.iscreensdk.utils.ISCREEN_SHAREDPREFERANCE
import com.rockstreamer.iscreensdk.utils.iScreenSDKInit
import com.rockstreamer.iscreensdk.utils.loginState
import org.koin.android.ext.koin.androidContext
import org.koin.core.context.startKoin

class App: Application() {

    override fun onCreate() {
        super.onCreate()
        loginState = getSharedPreferences(ISCREEN_SHAREDPREFERANCE, Context.MODE_PRIVATE)
        iScreenSDKInit(apiToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDE0OSwicHJvdmlkZXJfaWQiOiJNbjdaNnpXN2QyWkpLZktlSGJnOFZFNnNSMXoyIiwicm9sZSI6MCwidXNlcm5hbWUiOiIrODgwMTc3ODQ3NDMzMyIsInBsYXRmb3JtIjoiaXNjcmVlbiIsInN1YnNjcmliZSI6dHJ1ZSwicGFja2FnZUluZm8iOnsibmFtZSI6Ik1vbnRobHlTdWJzICggRXhwaXJlIEF0IDIwMjQtMDEtMTggKSIsImRlc2NyaXB0aW9uIjoiTW9udGhseVN1YnMgKCBFeHBpcmUgQXQgMjAyNC0wMS0xOCApIiwicHJpY2UiOiI4OSIsInVuaXQiOiJCRFQiLCJjb3VudHJ5Q29kZSI6IkJEIiwiY29sb3JDb2RlIjpudWxsLCJwcm9kdWN0SWQiOiJJU0NSRUVOX1NTTF9QTEFOXzEiLCJwYXltZW50TWV0aG9kVHlwZSI6InNzbGNvbW1lcnoiLCJleHBpcmVEYXRlIjoiMjAyNC0wMS0xOCJ9LCJpYXQiOjE3MDI5OTQyNTIsImV4cCI6MTcwMzA4MDY1Mn0.K6iC1sVhfqSU01lrhzoVSqP_vO-4-qvXbVPNcMYb4vO5m-kSd1HsEFIyeCHgTSrwi7szoXuY5gcd3skPtSQDeJ_uqkLysw01gCS9GZ1qrmhala_1VmLOw-U_W1psC19LDEcNvi-NM7JbfnZauIbiVJHNiZBOwUXpFbNq3K6cI0QJjIECy-xnqKkwiNTEhp3DsR-TxjEMDX8UP5MFJYu4WN1VR8bEC8xhGJA1VznmE7SAbcmopgPLhlqZqpIk-PGigTwlOZhkBLQ25pD031R1vQ35BxxEGAvYIQ6hdiTDmYs1-7Cv0urKMkhXjyJgaqaXxFpC0jFNtzzHmy9EtS8KI3DJiqwps84Q8PZ4HdsaauuT3eIToSIlbQ9sc8pCUICntDCOC5w9SdetwCnqPlRPuq31t22_awlOljGKFesTWSM2o-nBor9MSn4C5Nwywx7El5J-Bf-r9M44G59y2jTQXwdu0ivo1kC7SnYvs9bwHSxjdeo4g_1n3DTDsGRV5n-hVjlYpuiEqrQDoaoc8mgBLdCmhGXUO47EsZVX3ZryqVdcnli4QDb4fE9GAgqUHau5YB2SeTNnqkqNDJ1YvYsyM8utCFNmA2iDHkb-NjonPFnk8neH7IsQXxFH1Tm86sKqVVHwSKk2o-c0zyAFrfja_RlFtTSzREtbBFBmY7hwfus")
        startKoin {
            androidContext(this@App)
            modules(listOf(networkModule , contentModule , viewModelModule))
        }
    }
}