package com.rockstreamer.koinandroidexample

import android.app.Application
import android.content.Context
import com.rockstreamer.iscreensdk.di.contentModule
import com.rockstreamer.iscreensdk.di.networkModule
import com.rockstreamer.iscreensdk.di.viewModelModule
import com.rockstreamer.iscreensdk.utils.ISCREEN_SHAREDPREFERANCE
import com.rockstreamer.iscreensdk.utils.iScreenSDKInit
import com.rockstreamer.iscreensdk.utils.loginState
import org.koin.android.ext.koin.androidContext
import org.koin.core.context.startKoin

class App: Application() {

    override fun onCreate() {
        super.onCreate()
        loginState = getSharedPreferences(ISCREEN_SHAREDPREFERANCE, Context.MODE_PRIVATE)
        iScreenSDKInit(apiToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDc2Nzg2LCJwcm92aWRlcl9pZCI6InBob25lIiwicm9sZSI6MCwidXNlcm5hbWUiOiIrODgwMTc5MzcyNjc3NiIsInBsYXRmb3JtIjoiaXNjcmVlbiIsInBhcnRuZXIiOiJHUF9NWUdQIiwic3Vic2NyaWJlIjp0cnVlLCJwYWNrYWdlSW5mbyI6eyJuYW1lIjoiTW9udGhseVN1YnMgKCBFeHBpcmUgb24gMjAyNC0xMC0wNCApIiwiZGVzY3JpcHRpb24iOiJNb250aGx5U3VicyAoIEV4cGlyZSBvbiAyMDI0LTEwLTA0ICkiLCJwcmljZSI6Ijg5IiwidW5pdCI6IkJEVCIsImNvdW50cnlDb2RlIjoiQkQiLCJjb2xvckNvZGUiOm51bGwsInByb2R1Y3RJZCI6IklTQ1JFRU5fU1NMX1BMQU5fMSIsInBheW1lbnRNZXRob2RUeXBlIjoic3NsY29tbWVyeiIsImV4cGlyZURhdGUiOiIyMDI0LTEwLTA0In0sImlzVFZPRCI6ZmFsc2UsInR2b2RFeHBpcmVEYXRlIjoiMTk3MC0wMS0wMSIsImlhdCI6MTcyNTUyNjgzOSwiZXhwIjoxNzI1NjEzMjM5fQ.JNGptiaisNOyBpknzVlV_7QzvF5tRQ7Zsp-NrXsDXtdlmFiQMRqTRnw0zp8jCteMcoShynCn7OCc9moP6y5jRRUvE_XblfB6zwAkIjBJ25X-iP97FtSu5fIzL0GjqBBoYHEoYXfLbDhohkyJOcx_f-LXWvvbsaEx5qRnM6BDC4yEPGRkL6sO4V8KUWe6tlaGk0wBPNRyWJW-M2XVoIcngKG1rcfeL-ZxnTyxUCAunD5mi4UzqLWq_IuyEQQLOkhL9KhA47z-WfJS0QH1aaH5SDGsuzozx_14LnhIXQTsd6hNuPHyEInFhsR3vrhzOQkl0HsblI_vyWIETrY8TS8UfE1T7lfds0I4ppJ_XbAJtIyRc3-gvExNEIEY0G6x-FEqL-6vInZyi_7ejt6YsDKNpIxW-rQNCdIubzBP2M_TasFNlX-UxWLKm9q6GZjoLpDVUCmyGzZv1vPzsvX2jlbtdTLYiEXjlUnwLAufDFkpXb63vFLeAHYGXfwwO1vD6poJb3uPNf0kTmwsJm-GFS6iT0Sk9qN2VVQEZZlThCpLvkspUJOQJNL_pLYow2u83gb_0eyXOjEg1ZLzM_BGAyPGG2bBmphXjv6ec_GTOKVK5TJ2BAHCIG3cidYRpHVAWePkvEZUG9X7ApeF9qSAFEL5btB-pRaivQUuaxj9CSW2DE8")
        startKoin {
            androidContext(this@App)
            modules(listOf(networkModule , contentModule , viewModelModule))
        }
    }
}