package com.rockstreamer.koinandroidexample

import android.app.Application
import android.content.Context
import com.rockstreamer.iscreensdk.di.contentModule
import com.rockstreamer.iscreensdk.di.networkModule
import com.rockstreamer.iscreensdk.di.viewModelModule
import com.rockstreamer.iscreensdk.utils.ISCREEN_SHAREDPREFERANCE
import com.rockstreamer.iscreensdk.utils.iScreenSDKInit
import com.rockstreamer.iscreensdk.utils.loginState
import org.koin.android.ext.koin.androidContext
import org.koin.core.context.startKoin

class App: Application() {

    override fun onCreate() {
        super.onCreate()
        loginState = getSharedPreferences(ISCREEN_SHAREDPREFERANCE, Context.MODE_PRIVATE)
        iScreenSDKInit(apiToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mzk2MjM2LCJwcm92aWRlcl9pZCI6IjcyMzg0NzI5MzQ3Mjk4NDM3Iiwicm9sZSI6MCwidXNlcm5hbWUiOiJtaXRyYXN1bWkydDA4QGdtYWlsLmNvbSIsInBsYXRmb3JtIjoiaXNjcmVlbiIsInN1YnNjcmliZSI6dHJ1ZSwicGFja2FnZUluZm8iOnsibmFtZSI6Ik1vbnRobHlTdWJzICggRXhwaXJlIEF0IDIwMjMtMTItMjkgKSIsImRlc2NyaXB0aW9uIjoiTW9udGhseVN1YnMgKCBFeHBpcmUgQXQgMjAyMy0xMi0yOSApIiwicHJpY2UiOiI4OSIsInVuaXQiOiJCRFQiLCJjb3VudHJ5Q29kZSI6IkJEIiwiY29sb3JDb2RlIjpudWxsLCJwcm9kdWN0SWQiOiJJU0NSRUVOX1NTTF9QTEFOXzEiLCJwYXltZW50TWV0aG9kVHlwZSI6InNzbGNvbW1lcnoiLCJleHBpcmVEYXRlIjoiMjAyMy0xMi0yOSJ9LCJpYXQiOjE3MDEyODU1MDUsImV4cCI6MTcwMTM3MTkwNX0.jQoTyolg5ywB8367LL1p_LZipsAdcwSY-iaAvhLUaZM_Vq9V2Srggp5H5Dbuh9lZd48wg-himy488MyyKoL9TTgzB4bLNvWTOhpuKr2VJyAuIZFJwEctn-mKBT4cO--3WAkawOg6-wo7Kxdxk7ClC20PALRpStVREkwGbMQSEgXdMOdirCu4EJgzoD6GycTP-alE3IcX6_HEFEHggBTf-oulbR7MLLmy9chSGKCI07LwTiHoTGZLkg-jVxHCrq6oiVJLjQq2hXhZ3R2HYPVA1_9TgEjxT14agDchNA8gCshF1j8WaWYybvKb6OybjDnJY8pm3uj6j3v7zbkhe9XQU2CotHb3_cfxZpPveYH364EpHFZ88f75rn0Smp0PxWshcqJcnNk1j6RAXS0dnvzslB0T9s2upKBIgEnOnCBuK-OHhdn-uLkbZ3Wn3AusLZ-WkkIzC0JC4q_12ZsWt16MiPGnInsjr9V_zZ77GbJjlV2XpVlRj2mV3weOnBhQgdMcBBXq2Ixgcp8_VAPmoPs_-WiHq5sGyrNsB3kerCCB32juzpAX293y2JefspwdcMFtt7Tb0WJXlo5KS3tJANLH3_d4F2aD_q9HhtbFyq7_mhn_cUc4y7vL-DBTc4FUCyLZrKXYj13It_iyXwYVLLMYAFhTs4nKjH_6XbFeQYOFA0k")
        startKoin {
            androidContext(this@App)
            modules(listOf(networkModule , contentModule , viewModelModule))
        }
    }
}